# EcoXpert Pro - Main Configuration
# Premium Minecraft Economy Plugin
# https://github.com/koyere/ecoxpert

# Plugin Settings
plugin:
  # Debug mode for development
  debug: false
  # Configuration mode: 'advanced' exposes all module options; 'simple' applies curated defaults
  # and only a few top-level knobs are considered.
  config_mode: "advanced"
  
  # Language for messages (ISO 639-1 codes)
  language: "en"
  
  # Metrics collection (bStats)
  metrics:
    enabled: true
  
  # Update checking
  updates:
    check-enabled: true
    # Spigot resource id (legacy endpoint). If 0, uses check-url or skips
    resource-id: 0
    # Custom URL returning plain latest version string (optional)
    check-url: ""
    # Download page to show admins when update is available
    download-url: "https://github.com/koyere/ecoxpert"
    notify-admins: true
    check-interval: 21600 # 6 hours in seconds

# Educational messages (player-facing context)
education:
  enabled: true
  broadcasts:
    cycle: true     # Broadcast economic cycle changes
    events: true    # Broadcast educational line when an event starts
    policy: true    # Notify player on policy applications (e.g., wealth tax)
  cooldowns:
    cycle_minutes: 30           # Minimum minutes between cycle broadcasts
    events_minutes: 10          # Minimum minutes between event broadcasts
    policy_player_minutes: 60   # Per-player cooldown for policy notifications

# Database Configuration
database:
  # Database type: "sqlite" or "mysql"
  type: "sqlite"
  
  # SQLite settings
  sqlite:
    file: "ecoxpert.db"
    
  # MySQL settings (used when type is "mysql")
  mysql:
    # MySQL server hostname or IP
    host: "localhost"
    # MySQL server port (default: 3306)
    port: 3306
    # Database name (will be created if it doesn't exist)
    database: "ecoxpert"
    # MySQL user with CREATE/INSERT/SELECT/UPDATE privileges
    username: "username"
    password: "password"

    # SSL/TLS Configuration
    use-ssl: false
    # Allow public key retrieval for authentication (MySQL 8.0+)
    allow-public-key-retrieval: false

    # Character Encoding & Collation
    # EcoXpert automatically handles charset compatibility:
    # - Primary: utf8mb4_unicode_ci (supports full emoji/unicode range)
    # - Fallback: utf8_general_ci (for older MySQL versions < 5.5.3)
    # The plugin will auto-detect charset support and fallback if needed.
    # Recommended MySQL versions:
    # - MySQL 5.7.x or newer: Full utf8mb4 support
    # - MySQL 8.0.x or newer: Recommended, best performance
    # - MariaDB 10.2+: Full compatibility with utf8mb4

    # Connection pool settings
    pool:
      # Maximum connections in pool (default: 10)
      maximum-pool-size: 10
      # Minimum idle connections (default: 2)
      minimum-idle: 2
      # Connection timeout (milliseconds, default: 30000)
      connection-timeout: 30000
      # Idle timeout before connection close (milliseconds, default: 600000 = 10 min)
      idle-timeout: 600000
      # Maximum lifetime of a connection (milliseconds, default: 1800000 = 30 min)
      max-lifetime: 1800000

    # Troubleshooting MySQL Connection Issues
    # =========================================
    # ERROR: "Unsupported character encoding 'utf8mb4'"
    # SOLUTION: Your MySQL server doesn't support utf8mb4 charset.
    # Options:
    # 1. Upgrade MySQL to 5.7.7+ or MariaDB 10.2+
    # 2. Delete the EcoXpert database and restart the plugin
    #    (plugin will create it with utf8 fallback automatically)
    # 3. Manually create the database:
    #    CREATE DATABASE ecoxpert CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    #
    # ERROR: "Connection timeout" or "Communications link failure"
    # SOLUTION: Check MySQL server is running and accessible
    # - Verify host and port are correct
    # - Check MySQL is accepting connections
    # - Ensure firewall allows access
    # - Test: mysql -h <host> -u <user> -p
    #
    # ERROR: "Access denied for user"
    # SOLUTION: MySQL credentials are incorrect
    # - Verify username and password
    # - Ensure user has CREATE, SELECT, INSERT, UPDATE privileges
    # - Grant privileges:
    #   GRANT ALL PRIVILEGES ON ecoxpert.* TO 'username'@'localhost';

# Economy Settings
economy:
  # Default currency settings
  currency:
    name-singular: "dollar"
    name-plural: "dollars"
    symbol: "$"
    decimal-places: 2
    
  # Starting balance for new players
  starting-balance: 1000.0
  
  # Maximum balance limit (0 = unlimited)
  maximum-balance: 0
  
  # Transaction limits
  transaction-limits:
    # Minimum transaction amount
    minimum: 0.01
    # Maximum single transaction (0 = unlimited)
    maximum: 0
    # Daily transaction limit per player (0 = unlimited)
    daily-limit: 0

  # Migration from other economy providers (EssentialsX, CMI via Vault)
  migration:
    import_on_startup: true
    backup_before_import: true

# Cross-Platform Settings
cross-platform:
  # Bedrock Edition support
  bedrock:
    # Enable special handling for Bedrock players
    enabled: true
    # Use simplified interfaces for Bedrock
    simplified-gui: true
    # Alternative currency symbol for Bedrock compatibility
    currency-symbol: "$"
    
  # Server platform optimizations
  platform:
    # Enable Paper-specific optimizations
    paper-optimizations: true
    # Enable Folia regional threading support
    folia-support: true
    # Use async scheduler when available
    async-scheduler: true

# Module Configuration
modules:
  # Market module
  market:
    enabled: true
    config-file: "modules/market.yml"
    # Seed a minimal set of items on first run when the market is empty
    seed-on-empty: true
    
  # Banking module
  bank:
    enabled: true
    config-file: "modules/bank.yml"
    
  # Loans module
  loans:
    enabled: true
    config-file: "modules/loans.yml"
    
  # Economic events module
  events:
    enabled: true
    config-file: "modules/events.yml"
    
  # Professions module
  professions:
    enabled: true
    config-file: "modules/professions.yml"
    
  # Inflation control module
  inflation:
    enabled: true
    config-file: "modules/inflation.yml"
    
  # Integrations module
  integrations:
    enabled: true
    config-file: "modules/integrations.yml"

# Simple mode curated defaults (used when plugin.config_mode = 'simple')
simple:
  # Market tuning (applies to modules/market.yml pricing)
  market:
    max_price_change: 0.15          # gentler daily movement
    volatility_damping: 0.90        # smoother prices
    trend_analysis_hours: 24
  # Inflation policy target (fraction, e.g., 1.02 = 2%)
  inflation:
    target: 1.02
  # Basic wealth tax (fraction per cycle on high balances)
  policy:
    wealth_tax_rate: 0.005

# Performance Settings
performance:
  # Cache settings
  cache:
    # Player data cache duration (seconds)
    player-data: 300
    # Market data cache duration (seconds)
    market-data: 60
    # Balance cache duration (seconds)
    balance-cache: 30
    
  # Database optimization
  database-optimization:
    # Batch size for bulk operations
    batch-size: 100
    # Connection pool timeout (milliseconds)
    connection-timeout: 5000
    # Query timeout (milliseconds)
    query-timeout: 10000
    
  # Threading
  threading:
    # Core thread pool size
    core-threads: 2
    # Maximum thread pool size
    max-threads: 4
    # Thread keep-alive time (seconds)
    keep-alive: 60

# Logging Settings
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR
  level: "INFO"
  
  # Log specific events
  log-transactions: true
  log-market-changes: true
  log-admin-actions: true
  log-database-queries: false
  
  # Log file settings
  file-logging:
    enabled: false
    file: "logs/ecoxpert.log"
    max-size: "10MB"
    max-files: 5

# Security Settings
security:
  # Anti-exploit measures
  anti-exploit:
    enabled: true
    # Maximum transactions per minute per player
    transaction-rate-limit: 60
    # Suspicious activity detection
    activity-monitoring: true
    
  # Admin security
  admin-security:
    # Require confirmation for dangerous commands
    require-confirmation: true
    # Log all admin actions
    log-admin-actions: true

# DO NOT MODIFY - Configuration version for auto-updates
config-version: 1
